AWSTemplateFormatVersion: '2010-09-09'
Description: batch Mail
#----------------------------------------------
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: (required) Name of an existing EC2 key pair
  InstanceType: 
    Type: String 
    Default: t2.micro 
    ConstraintDescription : Must be a valid EC2 instance type
  AmiId:
    Type: AWS::EC2::Image::Id
    Description: (required) AMI ID
  PostfixMynetwork:
    Type: String
    Description: (required) Postfix mynetwork parameter
#----------------------------------------------
Resources:
  #-------------------Outbound Relay Mail Instance
  BatchLunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: BatchLunchTemplate
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        IamInstanceProfile:
          Name:
            Fn::ImportValue: MailPoC-IAM-For-Instance-Ec2BatchInstanceRolePlofile
        MetadataOptions:
          HttpEndpoint: enabled
          HttpTokens: required
          HttpPutResponseHopLimit: 1
        SecurityGroupIds:
          - Fn::ImportValue: MailPoC-SecurityGroups-BatchSGId
        Monitoring:
          Enabled: true
        TagSpecifications:
          -
            ResourceType: instance
            Tags:
              - Key: Name
                Value: MailPoC-InternalVPC-Batch
        UserData:
          Fn::Base64: !Sub | 
            #!/bin/bash -xe
            yum update -y 
            hostnamectl set-hostname batch-mail

            #バッチでのメール送信用にmailコマンドをインストール
            yum -y install mailx #ローカールでのmail送信テスト用にmailコマンドをインストール

            #Postfix設定
            cat > /etc/postfix/main.cf << EOL
            # Directory configurations
            queue_directory = /var/spool/postfix
            command_directory = /usr/sbin
            daemon_directory = /usr/libexec/postfix
            data_directory = /var/lib/postfix

            # process and network configurations 
            mail_owner = postfix
            inet_interfaces = all
            inet_protocols = ipv4
            mynetworks = ${PostfixMynetwork}
            mydestination = $myhostname, localhost.$mydomain, localhost
            unknown_local_recipient_reject_code = 550

            # alias configurations
            alias_maps = hash:/etc/aliases
            alias_database = hash:/etc/aliases

            # logging configurations
            debug_peer_level = 2
            debugger_command =
              PATH=/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin
              ddd $daemon_directory/$process_name $process_id & sleep 5

            # command and other configurations
            sendmail_path = /usr/sbin/sendmail.postfix
            newaliases_path = /usr/bin/newaliases.postfix
            mailq_path = /usr/bin/mailq.postfix
            setgid_group = postdrop
            html_directory = no
            manpage_directory = /usr/share/man
            sample_directory = /usr/share/doc/postfix-2.10.1/samples
            readme_directory = /usr/share/doc/postfix-2.10.1/README_FILES

            #relay
            relayhost = [10.3.154.80]:587
            EOL

            # restart postfix or system
            systemctl restart postfix




  BatchInstance: 
    Type: AWS::EC2::Instance 
    Properties:
      LaunchTemplate:
        LaunchTemplateName: BatchLunchTemplate
        Version: !GetAtt BatchLunchTemplate.LatestVersionNumber
      SubnetId: 
        Fn::ImportValue: MailPoC-InternalVPC-PrivateSubnet1Id
