AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Security Group
Parameters:
  InboundPrivateSubnet1Cidr:
    Description: CIDR Block of Inbound Private Subnet1
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be like 10.1.0.0/16
  InboundPrivateSubnet2Cidr:
    Description: CIDR Block of Inbound Private Subnet2
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be like 10.1.0.0/16
  InternalFrontSubnet1Cidr:
    Description: CIDR Block of Inbound Private Subnet1
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be like 10.1.0.0/16
  InternalFrontSubnet2Cidr:
    Description: CIDR Block of Inbound Private Subnet2
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be like 10.1.0.0/16


#-------------------------------------------------------
Resources:
  BatchSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: InternalVPC-BatchSG
      GroupDescription: SG for instances of batch and bounce mail receiving
      VpcId: 
        Fn::ImportValue: MailPoC-InternalVPC-VpcId
      Tags:
        - Key: Name
          Value: InternalVPC-BatchSG
  BatchSGReceivingMail1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref BatchSG
      IpProtocol: tcp
      FromPort: 587
      ToPort: 587
      CidrIp: !Ref InboundPrivateSubnet1Cidr
  BatchSGReceivingMail2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref BatchSG
      IpProtocol: tcp
      FromPort: 587
      ToPort: 587
      CidrIp: !Ref InboundPrivateSubnet2Cidr
  #--
  InboundRelayMailSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: DMZ-InboundVPC-RelayMailSG
      GroupDescription: SG for relay mail instances
      VpcId: 
        Fn::ImportValue: MailPoC-DMZ-Inbound-VPC-VpcId
      Tags:
        - Key: Name
          Value: DMZ-InboundVPC-RelayMailSG
  InboundRelayMailSGReceivingMail:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref InboundRelayMailSG
      IpProtocol: tcp
      FromPort: 25
      ToPort: 25
      CidrIp: 0.0.0.0/0
  InboundRelayMailSGReceivingMail2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref InboundRelayMailSG
      IpProtocol: tcp
      FromPort: 587
      ToPort: 587
      CidrIp: 0.0.0.0/0
  #--
  OutboundRelayMailSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: DMZ-OutboundVPC-RelayMailSG
      GroupDescription: SG for relay mail instances
      VpcId: 
        Fn::ImportValue: MailPoC-DMZ-Outbound-VPC-VpcId
      Tags:
        - Key: Name
          Value: DMZ-OutboundVPC-RelayMailSG
  OutboundRelayMailSGReceivingMail1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref OutboundRelayMailSG
      IpProtocol: tcp
      FromPort: 587
      ToPort: 587
      CidrIp: !Ref InternalFrontSubnet1Cidr
  OutboundRelayMailSGReceivingMail2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref OutboundRelayMailSG
      IpProtocol: tcp
      FromPort: 587
      ToPort: 587
      CidrIp: !Ref InternalFrontSubnet2Cidr
Outputs:
  #------------------ VPC
  BatchSGId:
    Description:  BatchSG ID
    Value: !Ref BatchSG
    Export:
      Name: !Sub "${AWS::StackName}-BatchSGId"
  InboundRelayMailSGId:
    Description:  InboundRelayMailSG ID
    Value: !Ref InboundRelayMailSG
    Export:
      Name: !Sub "${AWS::StackName}-InboundRelayMailSGId"
  OutboundRelayMailSGId:
    Description:  OutboundRelayMailSG ID
    Value: !Ref OutboundRelayMailSG
    Export:
      Name: !Sub "${AWS::StackName}-OutboundRelayMailSGId"