AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy VPCE(S3)
Resources:
  #------------------VPC Endpoint
  S3VpcEndpointInternalVPC:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcId:
        Fn::ImportValue: MailPoC-InternalVPC-VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      RouteTableIds:
        - Fn::ImportValue: MailPoC-InternalVPC-PublicSubnetRouteTableId
        - Fn::ImportValue: MailPoC-InternalVPC-PrivateSubnet1RouteTableId
        - Fn::ImportValue: MailPoC-InternalVPC-PrivateSubnet2RouteTableId
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:*'
            Resource:
              # Allow connections to the Amazon Linux yum repositories
              - "arn:aws:s3:::packages.*.amazonaws.com/*"
              - "arn:aws:s3:::repo.*.amazonaws.com/*"
              # Allow connections to the Amazon Linux2 yum repositories
              - "arn:aws:s3:::amazonlinux.*.amazonaws.com/*"
              # Allow connections to s3 buckets for CloudFormation custom resource request or a wait condition
              # - !Sub "arn:aws:s3:::cloudformation-custom-resource-response-${AWS::Region}"   # allow trafic to buckes
              # - !Sub "arn:aws:s3:::cloudformation-custom-resource-response-${AWS::Region}/*" # allow trafic to buckes
              # - !Sub "arn:aws:s3:::cloudformation-waitcondition-${AWS::Region}"              # waiting condition
              # - !Sub "arn:aws:s3:::cloudformation-waitcondition-${AWS::Region}/*"            # waiting condition
              # Allow SSM
              - !Sub "arn:aws:s3:::aws-ssm-${AWS::Region}/*"
              - !Sub "arn:aws:s3:::aws-windows-downloads-${AWS::Region}/*"
              - !Sub "arn:aws:s3:::region-birdwatcher-prod/*"
              - !Sub "arn:aws:s3:::patch-baseline-snapshot-${AWS::Region}/*"

  S3VpcEndpointInboundVPC:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcId:
        Fn::ImportValue: MailPoC-DMZ-Inbound-VPC-VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      RouteTableIds:
        - Fn::ImportValue: MailPoC-DMZ-Inbound-VPC-PublicSubnetRouteTableId
        - Fn::ImportValue: MailPoC-DMZ-Inbound-VPC-PrivateSubnet1RouteTableId
        - Fn::ImportValue: MailPoC-DMZ-Inbound-VPC-PrivateSubnet2RouteTableId
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:*'
            Resource:
              # Allow connections to the Amazon Linux yum repositories
              - "arn:aws:s3:::packages.*.amazonaws.com/*"
              - "arn:aws:s3:::repo.*.amazonaws.com/*"
              # Allow connections to the Amazon Linux2 yum repositories
              - "arn:aws:s3:::amazonlinux.*.amazonaws.com/*"
              # Allow connections to s3 buckets for CloudFormation custom resource request or a wait condition
              # - !Sub "arn:aws:s3:::cloudformation-custom-resource-response-${AWS::Region}"   # allow trafic to buckes
              # - !Sub "arn:aws:s3:::cloudformation-custom-resource-response-${AWS::Region}/*" # allow trafic to buckes
              # - !Sub "arn:aws:s3:::cloudformation-waitcondition-${AWS::Region}"              # waiting condition
              # - !Sub "arn:aws:s3:::cloudformation-waitcondition-${AWS::Region}/*"            # waiting condition
              # Allow SSM
              - !Sub "arn:aws:s3:::aws-ssm-${AWS::Region}/*"
              - !Sub "arn:aws:s3:::aws-windows-downloads-${AWS::Region}/*"
              - !Sub "arn:aws:s3:::region-birdwatcher-prod/*"
              - !Sub "arn:aws:s3:::patch-baseline-snapshot-${AWS::Region}/*"
